INSERT INTO PERSONS(PERSONID,FIRSTNAME,LASTNAME,AGE,CITY,DATEOFBIRTH)
VALUES(1,'SAYAK','DE',23,'HOWRAH','1998-10-22');
INSERT INTO PERSONS(PERSONID,FIRSTNAME,LASTNAME,AGE,CITY,DATEOFBIRTH)
VALUES(2,'SAYAN','SAHA',22,'HOWRAH','1999-11-22');
INSERT INTO PERSONS(PERSONID,FIRSTNAME,LASTNAME,AGE,CITY,DATEOFBIRTH)
VALUES(3,'GAUTAM','GAMBHIR',40,'DELHI','1982-1-10');
/*
DESC TABLE PERSONS;
SELECT * FROM PERSONS;
#FIRST CREATE TABLE FROM 
#PREVIOUS FILE THEN EXECUTE THIS CODE .This is multi line comment
#remove the multi line comment to show the table and drop after displaying
#to use this file again create table first
DROP TABLE PERSONS;*/

